In [1]:
import pandas as pd

In [2]:
df1 = pd.read_excel('clientes_comp.xlsx', sheet_name='Clientes1') 
df1

,CustomerID,Produto,Data de Publicação,QTD,Preço Único,CustomerName,Categoria do Produto,Forma de Pagamento,Análise,Venda Total
0,C5361,Phone,2024-03-05,8,618.83,Customer C5361,Office Supplies,Cash,1,4950.64
1,C6231,Laptop,2025-06-21,7,366.22,Customer C6231,Electronics,Debit Card,3,2563.54
2,C7704,Chair,2023-06-25,5,634.51,Customer C7704,Office Supplies,Credit Card,4,3172.55
3,C2923,Printer,2023-09-30,3,508.63,Customer C2923,Office Supplies,Gift Card,1,1525.89
4,C4847,Monitor,2023-04-03,4,452.06,Customer C4847,Electronics,Credit Card,2,1808.24
...,...,...,...,...,...,...,...,...,...,...
1795,C8238,Chair,2023-05-15,3,13.08,Customer C8238,Furniture,Online,4,39.24
1796,C8831,Monitor,2023-02-06,4,323.03,Customer C8831,Electronics,Debit Card,2,1292.12
1797,C6514,Phone,2024-08-08,5,129.86,Customer C6514,Electronics,Cash,3,649.30
1798,C3334,Printer,2024-02-03,3,493.15,Customer C3334,Furniture,Credit Card,5,1479.45
1799,C9593,Printer,2025-05-11,7,390.86,Customer C9593,Office Supplies,Online,4,2736.02

In [4]:
# Resumo dos dados: tipos de variáveis, nulos e valores distintos
resumo_dados = pd.DataFrame({
    "tipo_variavel": df1.dtypes,
    "nulos": df1.isna().sum(),
    "valores_distintos": df1.nunique(dropna=True)
}).reset_index().rename(columns={"index": "coluna"})

resumo_dados

                 coluna   tipo_variavel  nulos  valores_distintos
0            CustomerID             str      0               1642
1               Produto             str      0                  7
2    Data de Publicação  datetime64[us]      0                788
3                   QTD           int64      0                  8
4          Preço Único          float64      0               1777
5          CustomerName             str      0               1642
6  Categoria do Produto             str      0                  3
7    Forma de Pagamento             str      0                  5
8               Análise           int64      0                  5
9           Venda Total         float64      0               1792

In [6]:
quantidade_por_categoria = (
    df1.groupby("Categoria do Produto")["QTD"]
    .sum()
    .sort_values(ascending=False)
    .rename("Quantidade Vendida")
)

quantidade_por_categoria

Categoria do Produto
Office Supplies    2801
Furniture          2754
Electronics        2705
Name: Quantidade Vendida, dtype: int64

In [8]:
maior_venda_por_categoria = (
    df1.groupby(["Categoria do Produto", "Produto"])["QTD"]
    .sum()
    .rename("Quantidade Vendida")
    .reset_index()
)

maiores_produtos = maior_venda_por_categoria[
    maior_venda_por_categoria["Quantidade Vendida"]
    == maior_venda_por_categoria.groupby("Categoria do Produto")["Quantidade Vendida"]
    .transform("max")
]

display(quantidade_por_categoria.rename("Quantidade Vendida").to_frame())
display(maiores_produtos)

                      Quantidade Vendida
Categoria do Produto
Office Supplies                     2801
Furniture                           2754
Electronics                         2705

   Categoria do Produto  Produto  Quantidade Vendida
6           Electronics   Tablet                 487
9             Furniture   Laptop                 466
17      Office Supplies  Monitor                 439

In [9]:
vendas_por_categoria = (
    df1.groupby("Categoria do Produto")["Venda Total"]
    .sum()
    .sort_values(ascending=False)
    .rename("Total de Vendas")
)

display(vendas_por_categoria.to_frame())

valor_total_vendas = df1["Venda Total"].sum()
print(f"Valor total em vendas: R$ {valor_total_vendas:,.2f}")

                      Total de Vendas
Categoria do Produto
Office Supplies            1133462.57
Furniture                  1083282.25
Electronics                1049911.98

Valor total em vendas: R$ 3,266,656.80

In [10]:
# Valor arrecadado por categoria de produtos
vendas_por_categoria = (
    df1.groupby("Categoria do Produto")["Venda Total"]
    .sum()
    .sort_values(ascending=False)
    .rename("Total de Vendas")
)

display(vendas_por_categoria.to_frame())

for categoria, total in vendas_por_categoria.items():
    print(f"{categoria}: R$ {total:,.2f}")

                      Total de Vendas
Categoria do Produto
Office Supplies            1133462.57
Furniture                  1083282.25
Electronics                1049911.98

Office Supplies: R$ 1,133,462.57
Furniture: R$ 1,083,282.25
Electronics: R$ 1,049,911.98

In [11]:
produtos_ordenados = sorted(df1["Produto"].dropna().unique())
produtos_ordenados

['Chair', 'Desk', 'Laptop', 'Monitor', 'Phone', 'Printer', 'Tablet']

In [12]:
# Quantidade vendida e número de registros por forma de pagamento
vendas_por_pagamento = (
    df1.groupby("Forma de Pagamento")
    .agg(
        Quantidade_Vendida=("QTD", "sum"),
        Numero_de_Vendas=("QTD", "size")
    )
    .sort_values("Quantidade_Vendida", ascending=False)
)

# Total em vendas por produto
total_por_produto = (
    df1.groupby("Produto")["Venda Total"]
    .sum()
    .sort_values(ascending=False)
    .rename("Total de Vendas (R$)")
)

display(vendas_por_pagamento)
display(total_por_produto.to_frame())

                    Quantidade_Vendida  Numero_de_Vendas
Forma de Pagamento
Debit Card                        1821               396
Cash                              1630               356
Gift Card                         1618               353
Credit Card                       1614               349
Online                            1577               346

         Total de Vendas (R$)
Produto
Tablet              533091.00
Laptop              481721.40
Monitor             468632.80
Desk                454006.70
Phone               444989.72
Chair               443118.71
Printer             441096.47

In [15]:
# Quantidade vendida por produto
quantidade_por_produto = (
    df1.groupby("Produto")["QTD"]
    .sum()
    .sort_values(ascending=False)
    .rename("Quantidade Vendida")
)

# Soma das quantidades vendidas por categoria
display(quantidade_por_produto.to_frame())
display(quantidade_por_categoria.rename("Quantidade Vendida").to_frame())

         Quantidade Vendida
Produto
Tablet                 1316
Laptop                 1231
Monitor                1180
Desk                   1156
Chair                  1147
Phone                  1117
Printer                1113

                      Quantidade Vendida
Categoria do Produto
Office Supplies                     2801
Furniture                           2754
Electronics                         2705

In [16]:
# Quantidade total vendida de cada produto em cada categoria
tabela_quantidade_por_categoria = (
    df1.pivot_table(
        index="Categoria do Produto",
        columns="Produto",
        values="QTD",
        aggfunc="sum",
        fill_value=0
    )
)

display(tabela_quantidade_por_categoria)

Produto               Chair  Desk  Laptop  Monitor  Phone  Printer  Tablet
Categoria do Produto
Electronics             404   403     379      364    347      321     487
Furniture               342   318     466      377    427      407     417
Office Supplies         401   435     386      439    343      385     412

In [17]:
# Quantidade de produtos vendidos por dia
vendas_por_dia = (
    df1.groupby("Data de Publicação", as_index=False)["QTD"]
    .sum()
    .rename(columns={"QTD": "Quantidade Vendida"})
    .sort_values("Data de Publicação")
)

display(vendas_por_dia.head(10))

# Vendas diárias por categoria
vendas_por_dia_categoria = (
    df1.groupby(["Data de Publicação", "Categoria do Produto"], as_index=False)["QTD"]
    .sum()
    .rename(columns={"QTD": "Quantidade Vendida"})
    .sort_values(["Data de Publicação", "Quantidade Vendida"], ascending=[True, False])
)

display(vendas_por_dia_categoria.head(20))

# Categoria que mais vendeu em cada dia
categoria_mais_vendas_por_dia = (
    vendas_por_dia_categoria
    .sort_values(["Data de Publicação", "Quantidade Vendida"], ascending=[True, False])
    .drop_duplicates(subset="Data de Publicação")
    .rename(columns={"Categoria do Produto": "Categoria Mais Vendida"})
)

display(
    categoria_mais_vendas_por_dia[
        ["Data de Publicação", "Categoria Mais Vendida", "Quantidade Vendida"]
    ]
    .head(10)
)

# Resumo geral: qual categoria teve mais vendas ao longo dos dias
categoria_mais_vendas_total = (
    vendas_por_dia_categoria.groupby("Categoria do Produto")["Quantidade Vendida"]
    .sum()
    .sort_values(ascending=False)
)

display(categoria_mais_vendas_total)

  Data de Publicação  Quantidade Vendida
0         2023-01-01                  20
1         2023-01-02                   5
2         2023-01-03                  25
3         2023-01-04                   6
4         2023-01-05                   7
5         2023-01-06                  10
6         2023-01-07                   5
7         2023-01-08                   5
8         2023-01-09                  10
9         2023-01-10                   6

   Data de Publicação Categoria do Produto  Quantidade Vendida
0          2023-01-01          Electronics                   8
2          2023-01-01      Office Supplies                   7
1          2023-01-01            Furniture                   5
3          2023-01-02          Electronics                   5
6          2023-01-03      Office Supplies                  12
5          2023-01-03            Furniture                   7
4          2023-01-03          Electronics                   6
7          2023-01-04      Office Supplies                   6
8          2023-01-05            Furniture                   7
9          2023-01-06          Electronics                  10
10         2023-01-07          Electronics                   4
11         2023-01-07      Office Supplies                   1
13         2023-01-08            Furniture                   4
12         2023-01-08          Electronics                   1
15         2023-01-09      Office Supplies                   8
14         2023-01-09          Electronics                   2
17         2023-01-10      Office Supplies                   5
16         2023-01-10          Electronics                   1
18         2023-01-12      Office Supplies                   6
19         2023-01-13          Electronics                   7

   Data de Publicação Categoria Mais Vendida  Quantidade Vendida
0          2023-01-01            Electronics                   8
3          2023-01-02            Electronics                   5
6          2023-01-03        Office Supplies                  12
7          2023-01-04        Office Supplies                   6
8          2023-01-05              Furniture                   7
9          2023-01-06            Electronics                  10
10         2023-01-07            Electronics                   4
13         2023-01-08              Furniture                   4
15         2023-01-09        Office Supplies                   8
17         2023-01-10        Office Supplies                   5

Categoria do Produto
Office Supplies    2801
Furniture          2754
Electronics        2705
Name: Quantidade Vendida, dtype: int64

In [18]:
produtos_eletronicos = sorted(
    df1.loc[df1["Categoria do Produto"] == "Electronics", "Produto"].unique()
)

produtos_furniture = sorted(
    df1.loc[df1["Categoria do Produto"] == "Furniture", "Produto"].unique()
)

produtos_office_supplies = sorted(
    df1.loc[df1["Categoria do Produto"] == "Office Supplies", "Produto"].unique()
)

print("Electronics:", produtos_eletronicos)
print("Furniture:", produtos_furniture)
print("Office Supplies:", produtos_office_supplies)

Electronics: ['Chair', 'Desk', 'Laptop', 'Monitor', 'Phone', 'Printer', 'Tablet']
Furniture: ['Chair', 'Desk', 'Laptop', 'Monitor', 'Phone', 'Printer', 'Tablet']
Office Supplies: ['Chair', 'Desk', 'Laptop', 'Monitor', 'Phone', 'Printer', 'Tablet']